# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XMWuKa1tSxVKEiOuv2-0vJ3vfNv0q95
"""

import pandas as pd

titanik=pd.read_csv("/content/tested (1).csv")
print(titanik)